-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.21-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for andalan
CREATE DATABASE IF NOT EXISTS `andalan` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `andalan`;

-- Dumping structure for table andalan.clients
CREATE TABLE IF NOT EXISTS `clients` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `client_id` varchar(10) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `phone` varchar(25) DEFAULT NULL,
  `program` varchar(255) NOT NULL,
  `start_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `goal` varchar(255) NOT NULL,
  `birth_date` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.clients: ~2 rows (approximately)
INSERT INTO `clients` (`id`, `name`, `client_id`, `email`, `password`, `phone`, `program`, `start_date`, `goal`, `birth_date`, `is_active`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES
	(2, 'My Client', NULL, 'client@client.com', NULL, '12345678', '2x a Week | General Population', '2024-02-15 12:47:25', 'Mau ramping', '1989-12-31 10:00:00', 1, '2024-02-13 19:15:58', '2024-02-15 05:47:25', NULL, NULL),
	(3, 'Test Client', NULL, 'bstarz.66@gmail.com', NULL, '12345678', '1x a Week | General Population', '2024-02-15 10:00:00', 'Sixpack', '2010-05-09 10:00:00', 1, '2024-02-15 03:01:34', '2024-02-15 03:29:22', NULL, NULL);

-- Dumping structure for table andalan.failed_jobs
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table andalan.failed_jobs: ~0 rows (approximately)

-- Dumping structure for table andalan.head_trainings
CREATE TABLE IF NOT EXISTS `head_trainings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `head_date` timestamp NULL DEFAULT NULL,
  `head_notes` varchar(500) DEFAULT NULL,
  `tab_id` int(11) DEFAULT NULL,
  `client_id` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.head_trainings: ~1 rows (approximately)
INSERT INTO `head_trainings` (`id`, `head_date`, `head_notes`, `tab_id`, `client_id`, `updated_at`, `created_at`, `created_by`, `updated_by`) VALUES
	(1, '2024-03-09 17:00:00', NULL, 11, 2, '2024-03-10 06:47:00', '2024-03-10 06:47:00', 1, NULL),
	(2, '2024-03-10 17:00:00', 'Test', 11, 2, '2024-03-11 06:46:32', '2024-03-11 04:38:12', 1, 1);

-- Dumping structure for table andalan.master_category
CREATE TABLE IF NOT EXISTS `master_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category_name` varchar(225) NOT NULL DEFAULT '',
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.master_category: ~7 rows (approximately)
INSERT INTO `master_category` (`id`, `category_name`, `updated_at`, `created_at`, `created_by`, `updated_by`) VALUES
	(1, 'Hinge', NULL, '2024-02-22 17:35:28', NULL, NULL),
	(2, 'Power', NULL, '2024-02-22 17:35:28', NULL, NULL),
	(3, 'Pull', NULL, '2024-02-22 17:35:28', NULL, NULL),
	(4, 'Push', NULL, '2024-02-22 17:35:28', NULL, NULL),
	(5, 'Cardio', NULL, '2024-02-22 17:35:28', NULL, NULL),
	(6, 'Squat', NULL, '2024-02-22 17:35:28', NULL, NULL),
	(7, 'Hamstring', NULL, '2024-02-22 17:35:28', NULL, NULL);

-- Dumping structure for table andalan.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table andalan.migrations: ~4 rows (approximately)
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2019_08_19_000000_create_failed_jobs_table', 1),
	(4, '2019_12_14_000001_create_personal_access_tokens_table', 1);

-- Dumping structure for table andalan.movements
CREATE TABLE IF NOT EXISTS `movements` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT '',
  `categories` varchar(255) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=422 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.movements: ~421 rows (approximately)
INSERT INTO `movements` (`id`, `name`, `categories`, `updated_at`, `created_at`, `created_by`, `updated_by`) VALUES
	(1, 'Alternating Bridge March', 'Hamstring', NULL, NULL, NULL, NULL),
	(2, 'Alternating Bridge March Back on Bench', 'Hamstring', NULL, NULL, NULL, NULL),
	(3, 'Alternating Reverse Plank', 'Hamstring', NULL, NULL, NULL, NULL),
	(4, 'Alternating Reverse Plank Spring Ankle', 'Hamstring', NULL, NULL, NULL, NULL),
	(5, 'Bench Hamstring Curl', 'Hamstring', NULL, NULL, NULL, NULL),
	(6, 'Bench Single Leg Hamstring Curl', 'Hamstring', NULL, NULL, NULL, NULL),
	(7, 'Hooklying Calf Raise', 'Hamstring', NULL, NULL, NULL, NULL),
	(8, 'Hooklying Low Reach', 'Hamstring', NULL, NULL, NULL, NULL),
	(9, 'Hooklying Low Reach Midfoot', 'Hamstring', NULL, NULL, NULL, NULL),
	(10, 'Hooklying Low Reach Spring Ankle', 'Hamstring', NULL, NULL, NULL, NULL),
	(11, 'Hooklying Wall Tap', 'Hamstring', NULL, NULL, NULL, NULL),
	(12, 'Hooklying Wall Tap Up and Down', 'Hamstring', NULL, NULL, NULL, NULL),
	(13, 'Reverse Plank', 'Hamstring', NULL, NULL, NULL, NULL),
	(14, 'Single Leg Hooklying Calf Raise', 'Hamstring', NULL, NULL, NULL, NULL),
	(15, 'Single Leg Hooklying Low Reach', 'Hamstring', NULL, NULL, NULL, NULL),
	(16, 'Single Leg Hooklying Low Reach Midfoot', 'Hamstring', NULL, NULL, NULL, NULL),
	(17, 'Single Leg Hooklying Low Reach Oscilating', 'Hamstring', NULL, NULL, NULL, NULL),
	(18, 'Single Leg Hooklying Low Reach Oscilating w/ Slam Ball', 'Hamstring', NULL, NULL, NULL, NULL),
	(19, 'Single Leg Hooklying Low Reach Spring Ankle', 'Hamstring', NULL, NULL, NULL, NULL),
	(20, 'Slider Hamstring Curl', 'Hamstring', NULL, NULL, NULL, NULL),
	(21, 'Slider Hamstring Curl 2/1', 'Hamstring', NULL, NULL, NULL, NULL),
	(22, 'Slider Hamstring Curl Eccentric', 'Hamstring', NULL, NULL, NULL, NULL),
	(23, 'Slider Single Leg Hamstring Curl', 'Hamstring', NULL, NULL, NULL, NULL),
	(24, 'Slider Single Leg Hamstring Curl Eccentric', 'Hamstring', NULL, NULL, NULL, NULL),
	(25, 'Suspension Hamstring Curl', 'Hamstring', NULL, NULL, NULL, NULL),
	(26, 'Suspension Hamstring Curl 2/1', 'Hamstring', NULL, NULL, NULL, NULL),
	(27, 'Swiss Ball Hamstring Curl', 'Hamstring', NULL, NULL, NULL, NULL),
	(28, 'Swiss Ball Hamstring Curl 2/1', 'Hamstring', NULL, NULL, NULL, NULL),
	(29, 'Assisted Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(30, 'Barbell Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(31, 'Barbell Deadlift 2/1', 'Hinge', NULL, NULL, NULL, NULL),
	(32, 'Barbell Deadlift Overcoming Isometric', 'Hinge', NULL, NULL, NULL, NULL),
	(33, 'Barbell Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(34, 'Barbell Staggered Stance Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(35, 'Barbell Staggered Stance Deadlift Overcoming Isometric', 'Hinge', NULL, NULL, NULL, NULL),
	(36, 'Dumbbell Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(37, 'Dumbbell Deadlift 2/1', 'Hinge', NULL, NULL, NULL, NULL),
	(38, 'Dumbbell Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(39, 'Dumbbell Staggered Stance Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(40, 'Hinge', 'Hinge', NULL, NULL, NULL, NULL),
	(41, 'Jammer Arm Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(42, 'Jammer Arm Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(43, 'Kettlebell Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(44, 'Kettlebell Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(45, 'Kettlebell Deadlift 2/1', 'Hinge', NULL, NULL, NULL, NULL),
	(46, 'Kettlebell Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(47, 'Kettlebell Staggered Stance Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(48, 'Kettlebell Staggered Stance Swing', 'Hinge', NULL, NULL, NULL, NULL),
	(49, 'Kettlebell Swing', 'Hinge', NULL, NULL, NULL, NULL),
	(50, 'Landmine Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(51, 'Landmine Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(52, 'Low Cable Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(53, 'Low Cable Staggered Stance Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(54, 'Romanian Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(55, 'Single Leg Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(56, 'Single Leg Turn', 'Hinge', NULL, NULL, NULL, NULL),
	(57, 'Single Leg Turn w/ Perturbation', 'Hinge', NULL, NULL, NULL, NULL),
	(58, 'Staggered Stance Deadlift Spring Ankle', 'Hinge', NULL, NULL, NULL, NULL),
	(59, 'Sumo Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(60, 'Transformer Bar Hinge Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(61, 'Trap Bar Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(62, 'Trap Bar Deadlift 2/1', 'Hinge', NULL, NULL, NULL, NULL),
	(63, 'Trap Bar Staggered Stance Deadlift', 'Hinge', NULL, NULL, NULL, NULL),
	(64, '45? Counter Slide', 'Power', NULL, NULL, NULL, NULL),
	(65, '45? Counter Slide Double', 'Power', NULL, NULL, NULL, NULL),
	(66, '45? Slide', 'Power', NULL, NULL, NULL, NULL),
	(67, '45? Slide Double', 'Power', NULL, NULL, NULL, NULL),
	(68, '90? Counter Slide', 'Power', NULL, NULL, NULL, NULL),
	(69, '90? Counter Slide Double', 'Power', NULL, NULL, NULL, NULL),
	(70, '90? Slide', 'Power', NULL, NULL, NULL, NULL),
	(71, '90? Slide Double', 'Power', NULL, NULL, NULL, NULL),
	(72, 'Alternating Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(73, 'Alternating Pogo', 'Power Cardio', NULL, NULL, NULL, NULL),
	(74, 'Alternating Reverse Lunge w/ Kettlebell Swing', 'Power Cardio', NULL, NULL, NULL, NULL),
	(75, 'Alternating Sagittal Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(76, 'Alternating Sagittal/Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(77, 'Approach Jump', 'Power', NULL, NULL, NULL, NULL),
	(78, 'Approach Jump Double', 'Power', NULL, NULL, NULL, NULL),
	(79, 'Approach Jump Triple', 'Power', NULL, NULL, NULL, NULL),
	(80, 'Ball 90? Punch', 'Power', NULL, NULL, NULL, NULL),
	(81, 'Ball Approach Punch', 'Power', NULL, NULL, NULL, NULL),
	(82, 'Ball Chest Pass Rhythm', 'Power', NULL, NULL, NULL, NULL),
	(83, 'Ball Fake Slam to Split Squat', 'Power', NULL, NULL, NULL, NULL),
	(84, 'Ball Open Step Side to Side Scoop Pass', 'Power Cardio', NULL, NULL, NULL, NULL),
	(85, 'Ball Scoop Pass', 'Power', NULL, NULL, NULL, NULL),
	(86, 'Ball Side Step Side to Side Scoop Pass', 'Power Cardio', NULL, NULL, NULL, NULL),
	(87, 'Ball Side to Side (Open Step) Punch', 'Power', NULL, NULL, NULL, NULL),
	(88, 'Ball Side to Side (Open Step) Punch w/ Band Resistance', 'Power', NULL, NULL, NULL, NULL),
	(89, 'Ball Single Leg Toss', 'Power', NULL, NULL, NULL, NULL),
	(90, 'Ball Single Leg Toss from Depth Drop', 'Power', NULL, NULL, NULL, NULL),
	(91, 'Ball Single Leg Toss from Drop', 'Power', NULL, NULL, NULL, NULL),
	(92, 'Ball Skater Side to Side Scoop Pass', 'Power Cardio', NULL, NULL, NULL, NULL),
	(93, 'Ball Slam', 'Power', NULL, NULL, NULL, NULL),
	(94, 'Ball Staggered Stance Toss', 'Power', NULL, NULL, NULL, NULL),
	(95, 'Ball Staggered Stance Toss from Depth Drop', 'Power', NULL, NULL, NULL, NULL),
	(96, 'Ball Staggered Stance Toss from Drop', 'Power', NULL, NULL, NULL, NULL),
	(97, 'Ball Stepping Scoop Pass', 'Power', NULL, NULL, NULL, NULL),
	(98, 'Ball Supine Chest Pass', 'Power', NULL, NULL, NULL, NULL),
	(99, 'Ball Toss', 'Power', NULL, NULL, NULL, NULL),
	(100, 'Ball Toss from Depth Drop', 'Power', NULL, NULL, NULL, NULL),
	(101, 'Ball Toss from Drop', 'Power', NULL, NULL, NULL, NULL),
	(102, 'BallStepping Chest Pass', 'Power', NULL, NULL, NULL, NULL),
	(103, 'Band Assisted Alternating Pogo', 'Power Cardio', NULL, NULL, NULL, NULL),
	(104, 'Band Assisted First Step', 'Power', NULL, NULL, NULL, NULL),
	(105, 'Band Assisted Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(106, 'Band Assisted Jump', 'Power', NULL, NULL, NULL, NULL),
	(107, 'Band Assisted Pogo', 'Power Cardio', NULL, NULL, NULL, NULL),
	(108, 'Band Assisted Single Leg Pogo', 'Power Cardio', NULL, NULL, NULL, NULL),
	(109, 'Band Assisted Staggered Stance Jump', 'Power', NULL, NULL, NULL, NULL),
	(110, 'Band Resisted Broad Jump', 'Power', NULL, NULL, NULL, NULL),
	(111, 'Band Resisted Cross Step from Open Step (Power)', 'Power', NULL, NULL, NULL, NULL),
	(112, 'Band Resisted Lay Up Step', 'Power', NULL, NULL, NULL, NULL),
	(113, 'Band Resisted Slide', 'Power', NULL, NULL, NULL, NULL),
	(114, 'Band Resisted Step Up', 'Power', NULL, NULL, NULL, NULL),
	(115, 'Band Resisted Step Up w/ Initial Step', 'Power', NULL, NULL, NULL, NULL),
	(116, 'Bound', 'Power', NULL, NULL, NULL, NULL),
	(117, 'Box Cross Step Jump', 'Power', NULL, NULL, NULL, NULL),
	(118, 'Box Hop Land on Two', 'Power', NULL, NULL, NULL, NULL),
	(119, 'Box Jump', 'Power', NULL, NULL, NULL, NULL),
	(120, 'Box Jump from Depth Drop', 'Power', NULL, NULL, NULL, NULL),
	(121, 'Box Jump from Drop', 'Power', NULL, NULL, NULL, NULL),
	(122, 'Box Slide Jump', 'Power', NULL, NULL, NULL, NULL),
	(123, 'Box Slide, Cross Step Jump', 'Power', NULL, NULL, NULL, NULL),
	(124, 'Box Split Jump Land on Two', 'Power', NULL, NULL, NULL, NULL),
	(125, 'Broad Jump', 'Power', NULL, NULL, NULL, NULL),
	(126, 'Broad Jump Continuous', 'Power', NULL, NULL, NULL, NULL),
	(127, 'Broad Jump Double', 'Power', NULL, NULL, NULL, NULL),
	(128, 'Broad Jump Triple', 'Power', NULL, NULL, NULL, NULL),
	(129, 'Counter Slide', 'Power', NULL, NULL, NULL, NULL),
	(130, 'Counter Slide Double', 'Power', NULL, NULL, NULL, NULL),
	(131, 'Cross Step from Open Step (Power)', 'Power', NULL, NULL, NULL, NULL),
	(132, 'Cross Step from Open Step (Rhythm)', 'Power', NULL, NULL, NULL, NULL),
	(133, 'Flying Sprint', 'Power Cardio', NULL, NULL, NULL, NULL),
	(134, 'Forward Lunge w/ Vipr Swing', 'Power Cardio', NULL, NULL, NULL, NULL),
	(135, 'Jump from Depth Drop', 'Power', NULL, NULL, NULL, NULL),
	(136, 'Jump from Drop', 'Power', NULL, NULL, NULL, NULL),
	(137, 'Kettlebell Snatch', 'Power', NULL, NULL, NULL, NULL),
	(138, 'Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(139, 'Lateral Jump', 'Power Cardio', NULL, NULL, NULL, NULL),
	(140, 'Line Alternating Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(141, 'Line Alternating Sagittal Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(142, 'Line Alternating Sagittal/Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(143, 'Line Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(144, 'Line Lateral Jump', 'Power Cardio', NULL, NULL, NULL, NULL),
	(145, 'Line Sagittal Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(146, 'Line Sagittal Jump', 'Power Cardio', NULL, NULL, NULL, NULL),
	(147, 'Line Sagittal/Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(148, 'Line Sagittal/Lateral Jump', 'Power Cardio', NULL, NULL, NULL, NULL),
	(149, 'Open Step Side to Side', 'Power Cardio', NULL, NULL, NULL, NULL),
	(150, 'Pogo', 'Power Cardio', NULL, NULL, NULL, NULL),
	(151, 'Reverse Lunge w/ Kettlebell Swing', 'Power Cardio', NULL, NULL, NULL, NULL),
	(152, 'Reverse Lunge w/ Vipr Swing', 'Power Cardio', NULL, NULL, NULL, NULL),
	(153, 'Sagittal Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(154, 'Sagittal Jump', 'Power Cardio', NULL, NULL, NULL, NULL),
	(155, 'Sagittal/Lateral Hop', 'Power Cardio', NULL, NULL, NULL, NULL),
	(156, 'Sagittal/Lateral Jump', 'Power Cardio', NULL, NULL, NULL, NULL),
	(157, 'Side Step Side to Side', 'Power Cardio', NULL, NULL, NULL, NULL),
	(158, 'Side to Side (Open Step) Jab', 'Power', NULL, NULL, NULL, NULL),
	(159, 'Side to Side (Open Step) Jab w/ Band Resistance', 'Power', NULL, NULL, NULL, NULL),
	(160, 'Single Leg Bound', 'Power', NULL, NULL, NULL, NULL),
	(161, 'Single Leg Pogo', 'Power Cardio', NULL, NULL, NULL, NULL),
	(162, 'Skater Side to Side', 'Power Cardio', NULL, NULL, NULL, NULL),
	(163, 'Slide Double', 'Power', NULL, NULL, NULL, NULL),
	(164, 'Split Jump', 'Power', NULL, NULL, NULL, NULL),
	(165, 'Split Jump Double', 'Power', NULL, NULL, NULL, NULL),
	(166, 'Split Jump from Depth Drop', 'Power', NULL, NULL, NULL, NULL),
	(167, 'Split Jump from Drop', 'Power', NULL, NULL, NULL, NULL),
	(168, 'Split Jump Triple', 'Power', NULL, NULL, NULL, NULL),
	(169, 'Sprint', 'Power Cardio', NULL, NULL, NULL, NULL),
	(170, 'Sprint Slide', 'Power Cardio', NULL, NULL, NULL, NULL),
	(171, 'Vipr 45? Open Step Power (Double)', 'Power', NULL, NULL, NULL, NULL),
	(172, 'Vipr 45? Open Step Power (Single)', 'Power', NULL, NULL, NULL, NULL),
	(173, 'Vipr 45? Open Step Power, Rhythm', 'Power', NULL, NULL, NULL, NULL),
	(174, 'Vipr 45? Open Step Power, Rhythm, Rhythm', 'Power', NULL, NULL, NULL, NULL),
	(175, 'Vipr 45? Open Step Rhythm', 'Power Cardio', NULL, NULL, NULL, NULL),
	(176, 'Vipr Cross Step Power (Double)', 'Power', NULL, NULL, NULL, NULL),
	(177, 'Vipr Cross Step Power (Single)', 'Power', NULL, NULL, NULL, NULL),
	(178, 'Vipr Cross Step Power, Rhythm', 'Power', NULL, NULL, NULL, NULL),
	(179, 'Vipr Cross Step Power, Rhythm, Rhythm', 'Power', NULL, NULL, NULL, NULL),
	(180, 'Vipr Cross Step Rhythm', 'Power Cardio', NULL, NULL, NULL, NULL),
	(181, 'Vipr Open Step Power (Double)', 'Power', NULL, NULL, NULL, NULL),
	(182, 'Vipr Open Step Power (Single)', 'Power', NULL, NULL, NULL, NULL),
	(183, 'Vipr Open Step Power, Rhythm', 'Power', NULL, NULL, NULL, NULL),
	(184, 'Vipr Open Step Power, Rhythm, Rhythm', 'Power', NULL, NULL, NULL, NULL),
	(185, 'Vipr Open Step Rhythm', 'Power Cardio', NULL, NULL, NULL, NULL),
	(186, 'Band Assisted Neutral Grip Pull Up', 'Pull', NULL, NULL, NULL, NULL),
	(187, 'Barbell Bentover Row', 'Pull', NULL, NULL, NULL, NULL),
	(188, 'Barbell Chest Supported Row', 'Pull', NULL, NULL, NULL, NULL),
	(189, 'Cable Half Kneeling Row', 'Pull', NULL, NULL, NULL, NULL),
	(190, 'Cable Half Kneeling Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(191, 'Cable Seated Row', 'Pull', NULL, NULL, NULL, NULL),
	(192, 'Cable Short Seated Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(193, 'Cable Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(194, 'Cable Tall Kneeling Row', 'Pull', NULL, NULL, NULL, NULL),
	(195, 'Cable Tall Kneeling Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(196, 'Dumbbell Chest Supported Alternating Row', 'Pull', NULL, NULL, NULL, NULL),
	(197, 'Dumbbell Chest Supported Alternating Row w/ Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(198, 'Dumbbell Chest Supported Row', 'Pull', NULL, NULL, NULL, NULL),
	(199, 'Dumbbell Chest Supported Row Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(200, 'Dumbbell Chest Supported Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(201, 'Dumbbell Renegade Row', 'Pull', NULL, NULL, NULL, NULL),
	(202, 'High Cable Half Kneeling Row', 'Pull', NULL, NULL, NULL, NULL),
	(203, 'High Cable Half Kneeling Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(204, 'High Cable Short Seated Row', 'Pull', NULL, NULL, NULL, NULL),
	(205, 'High Cable Short Seated Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(206, 'High Cable Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(207, 'High Cable Squated Row', 'Pull', NULL, NULL, NULL, NULL),
	(208, 'High Cable Squated Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(209, 'High Cable Tall Kneeling Row', 'Pull', NULL, NULL, NULL, NULL),
	(210, 'High Cable Tall Kneeling Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(211, 'Jammer Arm Bilateral Stance Row', 'Pull', NULL, NULL, NULL, NULL),
	(212, 'Jammer Arm Bilateral Stance Row Explosive', 'Pull', NULL, NULL, NULL, NULL),
	(213, 'Jammer Arm Bilateral Stance Row Explosive (Continuous)', 'Pull', NULL, NULL, NULL, NULL),
	(214, 'Jammer Arm Staggered Stance Row', 'Pull', NULL, NULL, NULL, NULL),
	(215, 'Jammer Arm Staggered Stance Row Explosive', 'Pull', NULL, NULL, NULL, NULL),
	(216, 'Jammer Arm Swing', 'Pull', NULL, NULL, NULL, NULL),
	(217, 'Landmine Bilateral Stance Row', 'Pull', NULL, NULL, NULL, NULL),
	(218, 'Landmine Staggered Stance Row', 'Pull', NULL, NULL, NULL, NULL),
	(219, 'Low Cable Half Kneeling Row', 'Pull', NULL, NULL, NULL, NULL),
	(220, 'Low Cable Half Kneeling Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(221, 'Low Cable Seated Row', 'Pull', NULL, NULL, NULL, NULL),
	(222, 'Low Cable Short Seated Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(223, 'Low Cable Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(224, 'Low Cable Tall Kneeling Row', 'Pull', NULL, NULL, NULL, NULL),
	(225, 'Low Cable Tall Kneeling Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(226, 'Neutral Grip Pull Up', 'Pull', NULL, NULL, NULL, NULL),
	(227, 'Neutral Grip Pull Up Eccentric', 'Pull', NULL, NULL, NULL, NULL),
	(228, 'Neutral Grip Pull Up Explosive', 'Pull', NULL, NULL, NULL, NULL),
	(229, 'Neutral Grip Pull Up Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(230, 'Suspension Archer Row', 'Pull', NULL, NULL, NULL, NULL),
	(231, 'Suspension Archer Row Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(232, 'Suspension Row', 'Pull', NULL, NULL, NULL, NULL),
	(233, 'Suspension Row 2/1', 'Pull', NULL, NULL, NULL, NULL),
	(234, 'Suspension Row Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(235, 'Suspension Row Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(236, 'Suspension Seated Row', 'Pull', NULL, NULL, NULL, NULL),
	(237, 'Suspension Single Arm Row', 'Pull', NULL, NULL, NULL, NULL),
	(238, 'Suspension Single Arm Row Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(239, 'Suspension Y Row 2/1', 'Pull', NULL, NULL, NULL, NULL),
	(240, 'Weighted Neutral Grip Pull Up', 'Pull', NULL, NULL, NULL, NULL),
	(241, 'Weighted Neutral Grip Pull Up Eccentric', 'Pull', NULL, NULL, NULL, NULL),
	(242, 'Weighted Neutral Grip Pull Up Isometric Hold', 'Pull', NULL, NULL, NULL, NULL),
	(243, 'Alternating Shoulder Tap', 'Push', NULL, NULL, NULL, NULL),
	(244, 'Band Assisted Push Up Plyometric', 'Push', NULL, NULL, NULL, NULL),
	(245, 'Barbell Abdominal Roll Out', 'Push', NULL, NULL, NULL, NULL),
	(246, 'Barbell Bench Press', 'Push', NULL, NULL, NULL, NULL),
	(247, 'Barbell Floor Press', 'Push', NULL, NULL, NULL, NULL),
	(248, 'Barbell Floor Press Overcoming Isometric', 'Push', NULL, NULL, NULL, NULL),
	(249, 'Bear', 'Push', NULL, NULL, NULL, NULL),
	(250, 'Cable Bilateral Stance Single Arm Press', 'Push', NULL, NULL, NULL, NULL),
	(251, 'Cable Staggered Stance Single Arm Press', 'Push', NULL, NULL, NULL, NULL),
	(252, 'Dead Bug', 'Push', NULL, NULL, NULL, NULL),
	(253, 'Dead Bug Contralateral', 'Push', NULL, NULL, NULL, NULL),
	(254, 'Dead Bug Hands Only', 'Push', NULL, NULL, NULL, NULL),
	(255, 'Dead Bug Ipsilateral', 'Push', NULL, NULL, NULL, NULL),
	(256, 'Dead Bug Legs Only', 'Push', NULL, NULL, NULL, NULL),
	(257, 'Dumbbell Bench Alternating Press', 'Push', NULL, NULL, NULL, NULL),
	(258, 'Dumbbell Bench Press', 'Push', NULL, NULL, NULL, NULL),
	(259, 'Dumbbell Bench Reciprocal Press', 'Push', NULL, NULL, NULL, NULL),
	(260, 'Dumbbell Bench Single Arm Press', 'Push', NULL, NULL, NULL, NULL),
	(261, 'Dumbbell Floor Alternating Press', 'Push', NULL, NULL, NULL, NULL),
	(262, 'Dumbbell Floor Hooklying Alternating Press', 'Push', NULL, NULL, NULL, NULL),
	(263, 'Dumbbell Floor Hooklying Press', 'Push', NULL, NULL, NULL, NULL),
	(264, 'Dumbbell Floor Hooklying Reciprocal Press', 'Push', NULL, NULL, NULL, NULL),
	(265, 'Dumbbell Floor Hooklying Single Arm Press', 'Push', NULL, NULL, NULL, NULL),
	(266, 'Dumbbell Floor Press', 'Push', NULL, NULL, NULL, NULL),
	(267, 'Dumbbell Floor Reciprocal Press', 'Push', NULL, NULL, NULL, NULL),
	(268, 'Dumbbell Floor Single Arm Press', 'Push', NULL, NULL, NULL, NULL),
	(269, 'Dumbbell Incline (*) Bench Alternating Press', 'Push', NULL, NULL, NULL, NULL),
	(270, 'Dumbbell Incline (*) Bench Press', 'Push', NULL, NULL, NULL, NULL),
	(271, 'Dumbbell Incline (*) Bench Reciprocal Press', 'Push', NULL, NULL, NULL, NULL),
	(272, 'Dumbbell Incline (*) Bench Single Arm Press', 'Push', NULL, NULL, NULL, NULL),
	(273, 'Elbow Plank', 'Push', NULL, NULL, NULL, NULL),
	(274, 'Feet Elevated Plank', 'Push', NULL, NULL, NULL, NULL),
	(275, 'Feet Elevated Push Up', 'Push', NULL, NULL, NULL, NULL),
	(276, 'Feet Elevated Push Up Isometric Hold', 'Push', NULL, NULL, NULL, NULL),
	(277, 'Heel Supported Hip Flexion', 'Push', NULL, NULL, NULL, NULL),
	(278, 'Heel Supported Plank', 'Push', NULL, NULL, NULL, NULL),
	(279, 'Hip Flexion', 'Push', NULL, NULL, NULL, NULL),
	(280, 'Incline Push Up', 'Push', NULL, NULL, NULL, NULL),
	(281, 'Incline Push Up', 'Push', NULL, NULL, NULL, NULL),
	(282, 'Jammer Arm 180? Punch', 'Push', NULL, NULL, NULL, NULL),
	(283, 'Jammer Arm Bilateral Stance Press', 'Push', NULL, NULL, NULL, NULL),
	(284, 'Jammer Arm Bilateral Stance Punch', 'Push', NULL, NULL, NULL, NULL),
	(285, 'Jammer Arm Single Arm Bilateral Stance Press', 'Push', NULL, NULL, NULL, NULL),
	(286, 'Jammer Arm Single Arm Bilateral Stance Punch', 'Push', NULL, NULL, NULL, NULL),
	(287, 'Jammer Arm Single Arm Staggered Stance Press', 'Push', NULL, NULL, NULL, NULL),
	(288, 'Jammer Arm Single Arm Staggered Stance Punch', 'Push', NULL, NULL, NULL, NULL),
	(289, 'Jammer Arm Staggered Stance Press', 'Push', NULL, NULL, NULL, NULL),
	(290, 'Jammer Arm Staggered Stance Punch', 'Push', NULL, NULL, NULL, NULL),
	(291, 'Landmine 90? Punch', 'Push', NULL, NULL, NULL, NULL),
	(292, 'Landmine 90? Punch', 'Push', NULL, NULL, NULL, NULL),
	(293, 'Landmine Bilateral Stance Press', 'Push', NULL, NULL, NULL, NULL),
	(294, 'Landmine Bilateral Stance Punch', 'Push', NULL, NULL, NULL, NULL),
	(295, 'Landmine Bilateral Stance Punch to Staggered Stance', 'Push', NULL, NULL, NULL, NULL),
	(296, 'Landmine H Press', 'Push', NULL, NULL, NULL, NULL),
	(297, 'Landmine H Punch', 'Push', NULL, NULL, NULL, NULL),
	(298, 'Landmine H Punch to Staggered Stance', 'Push', NULL, NULL, NULL, NULL),
	(299, 'Landmine Half Kneeling Press', 'Push', NULL, NULL, NULL, NULL),
	(300, 'Landmine Staggered Stance Press', 'Push', NULL, NULL, NULL, NULL),
	(301, 'Landmine Staggered Stance Press w/ Reach Through', 'Push', NULL, NULL, NULL, NULL),
	(302, 'Landmine Staggered Stance Punch', 'Push', NULL, NULL, NULL, NULL),
	(303, 'Landmine Tall Kneeling Press', 'Push', NULL, NULL, NULL, NULL),
	(304, 'Landmine Tall Kneeling Punch', 'Push', NULL, NULL, NULL, NULL),
	(305, 'Lazy Bear', 'Push', NULL, NULL, NULL, NULL),
	(306, 'Plank', 'Push', NULL, NULL, NULL, NULL),
	(307, 'Plank', 'Push', NULL, NULL, NULL, NULL),
	(308, 'Push Up', 'Push', NULL, NULL, NULL, NULL),
	(309, 'Push Up Explosive to Plate', 'Push', NULL, NULL, NULL, NULL),
	(310, 'Push Up Isometric Hold', 'Push', NULL, NULL, NULL, NULL),
	(311, 'Push Up Plyometric', 'Push', NULL, NULL, NULL, NULL),
	(312, 'Slider Abdominal Roll Out', 'Push', NULL, NULL, NULL, NULL),
	(313, 'Suspension Abdominal Roll Out', 'Push', NULL, NULL, NULL, NULL),
	(314, 'Suspension Hip Flexion', 'Push', NULL, NULL, NULL, NULL),
	(315, 'Suspension Plank', 'Push', NULL, NULL, NULL, NULL),
	(316, 'Suspension Push Up', 'Push', NULL, NULL, NULL, NULL),
	(317, 'Swiss Ball Abdominal Roll Out', 'Push', NULL, NULL, NULL, NULL),
	(318, 'Swiss Ball Plank', 'Push', NULL, NULL, NULL, NULL),
	(319, 'Barbell Front Squat', 'Squat', NULL, NULL, NULL, NULL),
	(320, 'Barbell High Back Squat', 'Squat', NULL, NULL, NULL, NULL),
	(321, 'Barbell High Back Squat Overcoming Isometric', 'Squat', NULL, NULL, NULL, NULL),
	(322, 'Barbell Low Back Squat', 'Squat', NULL, NULL, NULL, NULL),
	(323, 'Barbell Staggered Stance High Back Squat Overcoming Isometric', 'Squat', NULL, NULL, NULL, NULL),
	(324, 'Depth Squat', 'Squat', NULL, NULL, NULL, NULL),
	(325, 'Double Kettlebell Rack Depth Squat', 'Squat', NULL, NULL, NULL, NULL),
	(326, 'Double Kettlebell Rack Front Foot Elevated Split Squat', 'Squat', NULL, NULL, NULL, NULL),
	(327, 'Double Kettlebell Rack Pistol Squat', 'Squat', NULL, NULL, NULL, NULL),
	(328, 'Double Kettlebell Rack Single Leg Squat to Box', 'Squat', NULL, NULL, NULL, NULL),
	(329, 'Double Kettlebell Rack Skater Squat', 'Squat', NULL, NULL, NULL, NULL),
	(330, 'Double Kettlebell Rack Squat', 'Squat', NULL, NULL, NULL, NULL),
	(331, 'Double Kettlebell Rack Step Up', 'Squat', NULL, NULL, NULL, NULL),
	(332, 'Double Kettlebell Step Down', 'Squat', NULL, NULL, NULL, NULL),
	(333, 'Double Kettlebell Step Up w/ Knee Drive', 'Squat', NULL, NULL, NULL, NULL),
	(334, 'Dumbbell Depth Squat', 'Squat', NULL, NULL, NULL, NULL),
	(335, 'Dumbbell Goblet Squat', 'Squat', NULL, NULL, NULL, NULL),
	(336, 'Dumbbell Lateral Squat', 'Squat', NULL, NULL, NULL, NULL),
	(337, 'Dumbbell Single Leg Calf Raise', 'Squat', NULL, NULL, NULL, NULL),
	(338, 'Dumbbell Step Down', 'Squat', NULL, NULL, NULL, NULL),
	(339, 'Dumbbell Step Up', 'Squat', NULL, NULL, NULL, NULL),
	(340, 'Dumbbell Step Up w/ Knee Drive', 'Squat', NULL, NULL, NULL, NULL),
	(341, 'Forward Lunge', 'Squat', NULL, NULL, NULL, NULL),
	(342, 'Front Foot Elevated Split Squat', 'Squat', NULL, NULL, NULL, NULL),
	(343, 'Front Foot Elevated Split Squat Isometric Hold', 'Squat', NULL, NULL, NULL, NULL),
	(344, 'Front Foot Elevated Split Squat Spring Ankle', 'Squat', NULL, NULL, NULL, NULL),
	(345, 'Front Foot Elevated Split Squat Spring Ankle Isometric Hold', 'Squat', NULL, NULL, NULL, NULL),
	(346, 'Kettlebell Depth Squat', 'Squat', NULL, NULL, NULL, NULL),
	(347, 'Kettlebell Goblet Squat', 'Squat', NULL, NULL, NULL, NULL),
	(348, 'Kettlebell Lateral Squat', 'Squat', NULL, NULL, NULL, NULL),
	(349, 'Kettlebell Rack Front Foot Elevated Split Squat Contralateral', 'Squat', NULL, NULL, NULL, NULL),
	(350, 'Kettlebell Rack Lateral Lunge Contralateral', 'Squat', NULL, NULL, NULL, NULL),
	(351, 'Kettlebell Rack Lateral Squat Contralateral', 'Squat', NULL, NULL, NULL, NULL),
	(352, 'Kettlebell Rack Pistol Squat', 'Squat', NULL, NULL, NULL, NULL),
	(353, 'Kettlebell Rack Single Leg Squat to Box', 'Squat', NULL, NULL, NULL, NULL),
	(354, 'Kettlebell Rack Skater Squat', 'Squat', NULL, NULL, NULL, NULL),
	(355, 'Kettlebell Rack Step Down', 'Squat', NULL, NULL, NULL, NULL),
	(356, 'Kettlebell Rack Step Up Ipsilateral', 'Squat', NULL, NULL, NULL, NULL),
	(357, 'Kettlebell Rack Step Up w/ Knee Drive', 'Squat', NULL, NULL, NULL, NULL),
	(358, 'Kettlebell Single Leg Calf Raise', 'Squat', NULL, NULL, NULL, NULL),
	(359, 'Kettlebell Step Down', 'Squat', NULL, NULL, NULL, NULL),
	(360, 'Kettlebell Step Up', 'Squat', NULL, NULL, NULL, NULL),
	(361, 'Kettlebell Step Up w/ Knee Drive', 'Squat', NULL, NULL, NULL, NULL),
	(362, 'Lateral Lunge', 'Squat', NULL, NULL, NULL, NULL),
	(363, 'Lateral Squat', 'Squat', NULL, NULL, NULL, NULL),
	(364, 'Pistol Squat', 'Squat', NULL, NULL, NULL, NULL),
	(365, 'Rear Foot Elevated Split Squat', 'Squat', NULL, NULL, NULL, NULL),
	(366, 'Rear Foot Elevated Split Squat Isometric', 'Squat', NULL, NULL, NULL, NULL),
	(367, 'Rear Foot Elevated Split Squat Isometric Hold', 'Squat', NULL, NULL, NULL, NULL),
	(368, 'Rear Foot Elevated Split Squat Spring Ankle', 'Squat', NULL, NULL, NULL, NULL),
	(369, 'Rear Foot Elevated Split Squat Spring Ankle Isometric Hold', 'Squat', NULL, NULL, NULL, NULL),
	(370, 'Reverse Lunge', 'Squat', NULL, NULL, NULL, NULL),
	(371, 'Short Stance Split Squat', 'Squat', NULL, NULL, NULL, NULL),
	(372, 'Short Stance Split Squat Spring Ankle', 'Squat', NULL, NULL, NULL, NULL),
	(373, 'Single Leg Calf Raise', 'Squat', NULL, NULL, NULL, NULL),
	(374, 'Single Leg Partial Squat Isometric Hold (Lateral Step)', 'Squat', NULL, NULL, NULL, NULL),
	(375, 'Single Leg Partial Squat Isometric Hold (Sagittal Step)', 'Squat', NULL, NULL, NULL, NULL),
	(376, 'Single Leg Squat to Box', 'Squat', NULL, NULL, NULL, NULL),
	(377, 'Skater Squat', 'Squat', NULL, NULL, NULL, NULL),
	(378, 'Squat', 'Squat', NULL, NULL, NULL, NULL),
	(379, 'Step Down', 'Squat', NULL, NULL, NULL, NULL),
	(380, 'Step Up', 'Squat', NULL, NULL, NULL, NULL),
	(381, 'Step Up w/ Knee Drive', 'Squat', NULL, NULL, NULL, NULL),
	(382, 'Transformer Bar Front Squat', 'Squat', NULL, NULL, NULL, NULL),
	(383, 'Transformer Bar Goblet Squat', 'Squat', NULL, NULL, NULL, NULL),
	(384, 'Transformer Bar Goblet Squat Concentric', 'Squat', NULL, NULL, NULL, NULL),
	(385, 'Transformer Bar Goblet Squat Eccentric', 'Squat', NULL, NULL, NULL, NULL),
	(386, 'Transformer Bar Goblet Squat Isometric', 'Squat', NULL, NULL, NULL, NULL),
	(387, 'Transformer Bar Goblet Squat Oscilating', 'Squat', NULL, NULL, NULL, NULL),
	(388, 'Transformer Bar High Back Squat', 'Squat', NULL, NULL, NULL, NULL),
	(389, 'Transformer Bar Low Back Squat', 'Squat', NULL, NULL, NULL, NULL),
	(390, 'Transformer Bar Safety Squat Bar Squat', 'Squat', NULL, NULL, NULL, NULL),
	(391, 'Transformer Bar Safety Squat Bar Squat Concentric', 'Squat', NULL, NULL, NULL, NULL),
	(392, 'Transformer Bar Safety Squat Bar Squat Eccentric', 'Squat', NULL, NULL, NULL, NULL),
	(393, 'Transformer Bar Safety Squat Bar Squat Isometric', 'Squat', NULL, NULL, NULL, NULL),
	(394, 'Transformer Bar Safety Squat Bar Squat Oscilating', 'Squat', NULL, NULL, NULL, NULL),
	(395, 'Trap Bar Rear Foot Elevated Split Squat', 'Squat', NULL, NULL, NULL, NULL),
	(396, 'Trap Bar Rear Foot Elevated Split Squat Isometric Hold', 'Squat', NULL, NULL, NULL, NULL),
	(397, 'Vipr Single Leg Partial Squat Isometric Hold (Lateral Step)', 'Squat', NULL, NULL, NULL, NULL),
	(398, 'Vipr Single Leg Partial Squat Isometric Hold (Sagittal Step)', 'Squat', NULL, NULL, NULL, NULL),
	(399, 'Ball 90? Punch Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(400, 'Ball Approach Punch Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(401, 'Ball Side to Side (Open Step) Punch Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(402, 'Ball Side to Side (Open Step) Punch w/ Band Resistance Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(403, 'Ball Stepping Chest Pass Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(404, 'Ball Stepping Scoop Pass Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(405, 'Band Resisted Cross Step from Open Step (Pace)', 'Cardio', NULL, NULL, NULL, NULL),
	(406, 'Band Resisted Sprint', 'Cardio', NULL, NULL, NULL, NULL),
	(407, 'Cross Step from Open Step (Pace)', 'Cardio', NULL, NULL, NULL, NULL),
	(408, 'Cross Step Jump Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(409, 'Kettlebell Volley', 'Cardio', NULL, NULL, NULL, NULL),
	(410, 'Prowler Bound', 'Cardio', NULL, NULL, NULL, NULL),
	(411, 'Prowler Sprint', 'Cardio', NULL, NULL, NULL, NULL),
	(412, 'Reverse/Forward Lunge w/ Vipr Swing', 'Cardio', NULL, NULL, NULL, NULL),
	(413, 'Side to Side (Open Step) Jab w/ Band Resistance Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(414, 'Slide Jump Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(415, 'Slide, Cross Step Jump Continuous', 'Cardio', NULL, NULL, NULL, NULL),
	(416, 'Split Jump Rhythm', 'Cardio', NULL, NULL, NULL, NULL),
	(417, 'Sprint Slide Verbal Cue', 'Cardio', NULL, NULL, NULL, NULL),
	(418, 'Sprint Slide Visual Cue', 'Cardio', NULL, NULL, NULL, NULL),
	(419, 'Vipr 45? Open Step Power', 'Cardio', NULL, NULL, NULL, NULL),
	(420, 'Vipr Cross Step Power', 'Cardio', NULL, NULL, NULL, NULL),
	(421, 'Vipr Open Step Power', 'Cardio', NULL, NULL, NULL, NULL);

-- Dumping structure for table andalan.password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table andalan.password_resets: ~0 rows (approximately)

-- Dumping structure for table andalan.personal_access_tokens
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table andalan.personal_access_tokens: ~0 rows (approximately)

-- Dumping structure for table andalan.program_history
CREATE TABLE IF NOT EXISTS `program_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL DEFAULT 0,
  `program` varchar(255) DEFAULT NULL,
  `updated_by` varchar(200) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.program_history: ~0 rows (approximately)

-- Dumping structure for table andalan.subs
CREATE TABLE IF NOT EXISTS `subs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `training_id` int(11) NOT NULL,
  `client_id` int(11) NOT NULL,
  `tab_id` int(11) NOT NULL,
  `movement_id` int(11) NOT NULL,
  `movement_name` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(10) DEFAULT NULL,
  `sets` varchar(50) DEFAULT NULL,
  `t` varchar(50) DEFAULT NULL,
  `wt` varchar(50) DEFAULT NULL,
  `rest` varchar(50) DEFAULT NULL,
  `reps1` varchar(255) DEFAULT NULL,
  `reps2` varchar(255) DEFAULT NULL,
  `reps3` varchar(255) DEFAULT NULL,
  `reps4` varchar(255) DEFAULT NULL,
  `reps5` varchar(255) DEFAULT NULL,
  `reps6` varchar(255) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `head_training_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.subs: ~0 rows (approximately)
INSERT INTO `subs` (`id`, `training_id`, `client_id`, `tab_id`, `movement_id`, `movement_name`, `status`, `sets`, `t`, `wt`, `rest`, `reps1`, `reps2`, `reps3`, `reps4`, `reps5`, `reps6`, `updated_at`, `created_at`, `created_by`, `updated_by`, `head_training_id`) VALUES
	(3, 7, 2, 11, 72, 'Alternating Lateral Hop', 'Bad', '1', '2', '3', '4', NULL, NULL, NULL, NULL, NULL, NULL, '2024-03-11 09:07:00', '2024-03-11 09:07:00', 1, NULL, 2),
	(4, 6, 2, 11, 73, 'Alternating Pogo', 'Bad', '1', '2', '3', '4', NULL, NULL, NULL, NULL, NULL, NULL, '2024-03-11 09:23:12', '2024-03-11 09:23:12', 1, NULL, 1);

-- Dumping structure for table andalan.tabs
CREATE TABLE IF NOT EXISTS `tabs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tab_name` varchar(255) DEFAULT NULL,
  `client_id` int(11) DEFAULT NULL,
  `tab_date` timestamp NULL DEFAULT NULL,
  `tab_notes` varchar(300) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.tabs: ~2 rows (approximately)
INSERT INTO `tabs` (`id`, `tab_name`, `client_id`, `tab_date`, `tab_notes`, `updated_at`, `created_at`, `created_by`, `updated_by`) VALUES
	(11, 'Week 1', 2, NULL, NULL, '2024-03-04 00:54:49', '2024-03-04 00:54:49', 1, NULL),
	(12, 'Week 2', 2, NULL, NULL, '2024-03-11 04:44:23', '2024-03-11 04:44:23', 1, NULL);

-- Dumping structure for table andalan.trainings
CREATE TABLE IF NOT EXISTS `trainings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` timestamp NULL DEFAULT NULL,
  `client_id` int(11) NOT NULL,
  `tab_id` int(11) NOT NULL,
  `categories` varchar(225) DEFAULT '',
  `movement_id` int(11) NOT NULL,
  `movement_name` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(10) DEFAULT NULL,
  `sets` varchar(50) DEFAULT NULL,
  `t` varchar(50) DEFAULT NULL,
  `wt` varchar(50) DEFAULT NULL,
  `rest` varchar(50) DEFAULT NULL,
  `subs` varchar(1) DEFAULT 'N',
  `reps1` varchar(255) DEFAULT NULL,
  `reps2` varchar(255) DEFAULT NULL,
  `reps3` varchar(255) DEFAULT NULL,
  `reps4` varchar(255) DEFAULT NULL,
  `reps5` varchar(255) DEFAULT NULL,
  `reps6` varchar(255) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `head_training_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table andalan.trainings: ~4 rows (approximately)
INSERT INTO `trainings` (`id`, `date`, `client_id`, `tab_id`, `categories`, `movement_id`, `movement_name`, `status`, `sets`, `t`, `wt`, `rest`, `subs`, `reps1`, `reps2`, `reps3`, `reps4`, `reps5`, `reps6`, `updated_at`, `created_at`, `created_by`, `updated_by`, `head_training_id`) VALUES
	(4, '2024-03-09 17:00:00', 2, 11, '', 73, 'Alternating Pogo', 'Good', '1', '2', '3', '4', 'N', NULL, NULL, NULL, NULL, NULL, NULL, '2024-03-10 06:47:00', '2024-03-10 06:47:00', 1, NULL, 1),
	(5, '2024-03-10 17:00:00', 2, 11, '', 2, 'Alternating Bridge March Back on Bench', 'Good', '1', '2', '3', '4', 'N', '1', '1', '1', '1', '1', '1', '2024-03-11 09:03:05', '2024-03-11 04:38:12', 1, 1, 2),
	(6, '2024-03-09 17:00:00', 2, 11, '', 187, 'Barbell Bentover Row', 'Good', '3', '2', '1', '0', 'Y', '1', '2', '3', '4', '5', '6', '2024-03-11 09:23:12', '2024-03-11 08:19:59', 1, 1, 1),
	(7, '2024-03-10 17:00:00', 2, 11, '', 8, 'Hooklying Low Reach', 'Good', '1', '2', '3', '4', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, '2024-03-11 09:07:00', '2024-03-11 08:42:09', 1, 1, 2);

-- Dumping structure for table andalan.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `last_login` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN',
  `phone` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table andalan.users: ~2 rows (approximately)
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `last_login`, `password`, `role`, `phone`, `remember_token`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES
	(1, 'Finicode', 'finicodedigital@gmail.com', NULL, '2024-03-11 04:18:59', '$2y$10$UU9kucaD6b.7JP7SpsNMZ.7KKUrTaNVzVYYhns5uZmrguu7NtqkQe', 'SUPERADMIN', '', NULL, NULL, '2024-03-11 04:18:59', NULL, NULL),
	(8, 'Test User', 'test@gmail.com', NULL, '2024-02-12 18:49:46', '$2y$10$Q718w3dYN8NV2ECd6AOIuuPrP9aNb.IgIBbsqGXO/tuaiON0IFsrG', 'ADMIN', '12345678', NULL, '2024-02-07 18:32:13', '2024-02-15 04:05:07', NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
